### ISSUE TITLE
nextqa hard dataset

### ISSUE THREAD

**Issue by bxwldljh** [doc-doc/CoVGT#7]
hi, can you provide the links for atp-hard subset of nextqa dataset? many thanks to you!!!

**Comment by doc-doc** [comment]
Hi, please find the subset [here](https://drive.google.com/file/d/17kGNtSSpCgJOdOo52l_q5FMAD1ms4Hu3/view?usp=sharing).

**Comment by bxwldljh** [comment]
thank you so much!!!
